In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [8]:
#logistic Regression
modellr = LogisticRegression()
modellr.fit(X_train,y_train)
modellr.score(X_test,y_test)

C:\Users\ankit\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

In [6]:
#SVM
modelSVC = SVC()
modelSVC.fit(X_train,y_train)
modelSVC.score(X_test,y_test)

0.9851851851851852

In [7]:
#RandomForestClassifier
modelRFC = RandomForestClassifier()
modelRFC.fit(X_train,y_train)
modelRFC.score(X_test,y_test)

0.9685185185185186

In [ ]:
#In train_test_split, the data samples are picked randomly for training 
#everytime you run the model and you will probably see difference in the
#score each time you run. So you can't say that its perfect at one time, 
#because you will get diff results everytime.

In [9]:
#K-Fold Cross Validation
from sklearn.model_selection import KFold
kf = KFold(n_splits=3) #you can specify the no. of folds you want
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [11]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [ ]:
#as you can see above the three folds are(indices) [012][345][678]
#iteration1: train- 2,3 folds [345678], test-1 fold [012]
#iteration2: train- 1,3 folds [012678], test-2 fold [345]
#iteration3: train- 1,2 folds [012345], test-3 fold [678]

In [12]:
def get_score(model, X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [13]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

C:\Users\ankit\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

In [14]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9851851851851852

In [15]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9740740740740741

In [26]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [19]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))


C:\Users\ankit\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ankit\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

In [20]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [21]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [22]:
scores_rf

[0.9382303839732888, 0.9632721202003339, 0.9298831385642737]

In [31]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=3)

C:\Users\ankit\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ankit\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

array([0.92153589, 0.94156928, 0.91652755])

In [32]:
cross_val_score(SVC(),digits.data,digits.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [33]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=3)

array([0.94156928, 0.95659432, 0.93489149])

In [36]:
#Parameter tunning
scores1 = cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=10)
np.average(scores1)

0.9454593420235877